import type { z } from "zod";
import * as programsApi from "@/lib/api/programs";
import * as tutorsApi from "@/lib/api/tutors";
import * as achievementsApi from "@/lib/api/achievements";
import * as contactApi from "@/lib/api/contact";
import { createProgramSchema } from "@/modules/programs/program.validation";
import { createPackageSchema } from "@/modules/programs/package.validation";
import { createTutorSchema } from "@/modules/tutors/tutor.validation";
import { createEducationSchema } from "@/modules/tutors/education.validation";
import { createExperienceSchema } from "@/modules/tutors/experience.validation";
import { createAchievementSchema } from "@/modules/achievements/achievement.validation";
import { createContactLocationSchema, updateContactInformationSchema } from "@/modules/contact/contact.validation";
import { updateCompanyProfileSchema } from "@/modules/company/company.validation";
import { categoryLabels, achievementLabels, priceUnits } from "@/lib/ui/format";

export type Field = { name: string; label: string; type?: "text" | "textarea" | "number" | "email" | "url" | "select" | "checkbox" | "image"; required?: boolean; maxLength?: number; min?: number; max?: number; options?: Record<string,string>; hint?: string; initial?: string | number | boolean };
export type FormSpec = { fields: Field[]; schema: z.ZodType; folder?: "branding" | "programs" | "tutors" | "achievements" };
export type CmsRow = { id: string; [key: string]: unknown };
export type ResourceKey = "programs" | "packages" | "tutors" | "educations" | "experiences" | "achievements" | "locations";
export type ResourceDefinition = FormSpec & { title: string; singular: string; labelKey: string; secondaryKey: string; imageKey?: string; root?: boolean; children?: { key: ResourceKey; property: string; title: string }[]; create: (parentId: string, data: unknown) => Promise<unknown>; update: (id: string, data: unknown) => Promise<unknown>; remove: (id: string) => Promise<unknown>; restore?: (id: string) => Promise<unknown> };
const text = (name: string,label: string,maxLength = 255,required = false): Field => ({name,label,maxLength,required});
const area = (name: string,label: string,maxLength = 5000): Field => ({name,label,type:"textarea",maxLength});
const order: Field = { name:"display_order",label:"Urutan tampil",type:"number",min:0,max:2147483647,initial:0,hint:"Angka lebih kecil ditampilkan lebih dahulu." };
const slug: Field = { name:"slug",label:"Slug URL",required:true,maxLength:180,hint:"Huruf kecil, angka, dan tanda hubung. Mengubah slug akan mengubah URL detail." };
const year = (name: string,label: string): Field => ({name,label,type:"number",min:1900,max:2100});
const image = (name: string,label: string): Field => ({name,label,type:"image",hint:"JPEG, PNG, atau WebP; maksimal 5 MB. Unggah file atau tempel URL gambar."});
const select = (name: string,label: string,options: Record<string,string>): Field => ({name,label,type:"select",required:true,options});
export const resources: Record<ResourceKey,ResourceDefinition> = {
 programs: { title:"Program belajar",singular:"program",labelKey:"name",secondaryKey:"category",imageKey:"image_url",root:true,folder:"programs",schema:createProgramSchema,fields:[text("name","Nama program",150,true),slug,select("category","Kategori",categoryLabels),order,area("description","Deskripsi program"),image("image_url","Gambar program")],children:[{key:"packages",property:"program_packages",title:"Paket belajar"}],create:(_,data)=>programsApi.createProgram(createProgramSchema.parse(data)),update:(id,data)=>programsApi.updateProgram(id,createProgramSchema.parse(data)),remove:programsApi.deleteProgram,restore:(id)=>programsApi.updateProgram(id,{is_active:true}) },
 packages: { title:"Paket belajar",singular:"paket",labelKey:"name",secondaryKey:"price_unit",schema:createPackageSchema,fields:[text("name","Nama paket",150,true),{name:"price",label:"Harga (Rupiah)",type:"number",required:true,min:0,max:2147483647},select("price_unit","Satuan pembayaran",priceUnits),text("duration","Durasi",100),order,area("description","Deskripsi paket")],create:(id,data)=>programsApi.createProgramPackage(id,createPackageSchema.parse(data)),update:(id,data)=>programsApi.updateProgramPackage(id,createPackageSchema.parse(data)),remove:programsApi.deleteProgramPackage,restore:(id)=>programsApi.updateProgramPackage(id,{is_active:true}) },
 tutors: { title:"Tim tutor",singular:"tutor",labelKey:"name",secondaryKey:"specialization",imageKey:"photo_url",root:true,folder:"tutors",schema:createTutorSchema,fields:[text("name","Nama tutor",150,true),slug,text("title","Gelar / jabatan",100),text("specialization","Spesialisasi"),order,area("bio","Biografi",10000),image("photo_url","Foto tutor")],children:[{key:"educations",property:"tutor_educations",title:"Pendidikan"},{key:"experiences",property:"tutor_experiences",title:"Pengalaman"}],create:(_,data)=>tutorsApi.createTutor(createTutorSchema.parse(data)),update:(id,data)=>tutorsApi.updateTutor(id,createTutorSchema.parse(data)),remove:tutorsApi.deleteTutor,restore:(id)=>tutorsApi.updateTutor(id,{is_active:true}) },
 educations: { title:"Pendidikan",singular:"pendidikan",labelKey:"institution",secondaryKey:"field_of_study",schema:createEducationSchema,fields:[text("institution","Institusi",255,true),text("field_of_study","Bidang studi"),year("start_year","Tahun mulai"),year("end_year","Tahun selesai"),order,area("description","Deskripsi")],create:(id,data)=>tutorsApi.createTutorEducation(id,createEducationSchema.parse(data)),update:(id,data)=>tutorsApi.updateTutorEducation(id,createEducationSchema.parse(data)),remove:tutorsApi.deleteTutorEducation },
 experiences: { title:"Pengalaman",singular:"pengalaman",labelKey:"organization",secondaryKey:"position",schema:createExperienceSchema,fields:[text("organization","Organisasi",255,true),text("position","Posisi",150),year("start_year","Tahun mulai"),year("end_year","Tahun selesai"),order,area("description","Deskripsi")],create:(id,data)=>tutorsApi.createTutorExperience(id,createExperienceSchema.parse(data)),update:(id,data)=>tutorsApi.updateTutorExperience(id,createExperienceSchema.parse(data)),remove:tutorsApi.deleteTutorExperience },
 achievements: { title:"Prestasi siswa",singular:"prestasi",labelKey:"title",secondaryKey:"student_name",imageKey:"image_url",root:true,folder:"achievements",schema:createAchievementSchema,fields:[text("student_name","Nama siswa",150,true),text("title","Judul prestasi",255,true),select("achievement_type","Kategori prestasi",achievementLabels),year("year","Tahun"),text("student_school","Sekolah"),text("destination","Sekolah / kampus tujuan"),text("subject","Mata pelajaran",150),text("competition_name","Nama kompetisi"),text("competition_level","Tingkat kompetisi",150),order,{name:"is_featured",label:"Tampilkan sebagai prestasi unggulan",type:"checkbox",initial:false},area("description","Cerita prestasi",10000),image("image_url","Foto siswa / prestasi")],create:(_,data)=>achievementsApi.createAchievement(createAchievementSchema.parse(data)),update:(id,data)=>achievementsApi.updateAchievement(id,createAchievementSchema.parse(data)),remove:achievementsApi.deleteAchievement,restore:(id)=>achievementsApi.updateAchievement(id,{is_active:true}) },
 locations: { title:"Lokasi & cabang",singular:"lokasi",labelKey:"label",secondaryKey:"address",root:true,schema:createContactLocationSchema,fields:[text("label","Nama cabang",100),text("contact_person","Narahubung",150),{name:"address",label:"Alamat lengkap",type:"textarea",required:true},text("phone","Telepon",30),text("whatsapp","WhatsApp",30),{name:"google_maps_url",label:"URL Google Maps",type:"url"},order],create:(_,data)=>contactApi.createContactLocation(createContactLocationSchema.parse(data)),update:(id,data)=>contactApi.updateContactLocation(id,createContactLocationSchema.parse(data)),remove:contactApi.deleteContactLocation,restore:(id)=>contactApi.updateContactLocation(id,{is_active:true}) },
};
export const companyForm: FormSpec = { schema:updateCompanyProfileSchema,folder:"branding",fields:[text("name","Nama lembaga",150,true),text("tagline","Tagline"),area("description","Tentang lembaga",10000),area("history","Sejarah",10000),area("vision","Visi"),area("mission","Misi",10000),image("logo_url","Hero Image")] };
export const contactForm: FormSpec = { schema:updateContactInformationSchema,fields:[{name:"email",label:"Email",type:"email",maxLength:255},...[["instagram_url","Instagram"],["facebook_url","Facebook"],["tiktok_url","TikTok"],["youtube_url","YouTube"]].map(([name,label]): Field=>({name,label:`URL ${label}`,type:"url"}))] };
